### ISSUE TITLE
structure_compare issues

### ISSUE THREAD

**Issue by pqyNUS** [lmb-seq/nuc_tools#1]
Hi,

I tried to run structure_compare to compare between 2 n3d files, and i get the following error.

**nuc_tools structure_compare p3.chr2.n3d -i2 p4.chr2.n3d -o p3_p4**

Traceback (most recent call last):
  File "/hpctmp/obgpqy/nuc_tools/nuc_tools.py", line 63, in <module>
    main()
  File "/hpctmp/obgpqy/nuc_tools/nuc_tools.py", line 59, in main
    module.main(argv[1:])
  File "/hpctmp/obgpqy/nuc_tools/tools/structure_compare.py", line 436, in main
    bin_size, out_pdf_path, screen_gfx, rmsd_max, cmap)
  File "/hpctmp/obgpqy/nuc_tools/tools/structure_compare.py", line 337, in structure_compare
    bin_size, rmsd_max, cmap, pdf)
  File "/hpctmp/obgpqy/nuc_tools/tools/structure_compare.py", line 51, in plot_structure_compare
    coord_models1.append(coords_dict1[chromo][:,i1:j1])
TypeError: slice indices must be integers or None or have an __index__ method

But when I ran structure_compare on the n3d files inidividually, i dont get any errors.
May i know where could have gone wrong?

**Comment by tjs23** [comment]
This is now fixed; an bug from old Python 2 integer division.
